
name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:

        -uses: actions/chckout@v3

        -name: Install dependencies
          run: |
            cd frontend
            npm ci
        
        -name: Built the app
          run: |
            cd frontend
            npm run build
        
        -name: Running Component Tests
          run: |
            cd frontend
            npm run test
        
        -name: Start The app
          run: |
            cd frontend
            npm run start &
            npx wait-on --timeout 60000

        -name: Install Vercel CLI
          run: |
            cd frontend
            npm install --global vercel

        -name: Pull Vercel Environment Information
          run: |  
            cd frontend
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        -name: Build Project Artifacts
          run: |
            cd frontend
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
       
        -name: Deploy Project Artifacts
          run: |
            cd frontend 
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

        


