
name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  # push:
  #   branches-ignore:
  #     - production
  pull_request:
    branches-ignore:
      - production

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

        - uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            cd frontend
            npm ci
        
        # - name: Built the app
        #   run: |
        #     cd frontend
        #     npm run build
        
        - name: Running Component Tests
          run: |
            cd frontend
            npm run test


        - name: Start The app
          run: |
            cd frontend
            npm run start &
            npx wait-on --timeout 60000

        - name: Install Vercel CLI
          run: |
            cd frontend
            npm install --global vercel

        - name: Pull Vercel Environment Information
          run: |  
            cd frontend
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

        - name: Build Project Artifacts
          run: |
            cd frontend
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
       
        - name: Preview Deploy Project Artifacts
          run: |
            cd frontend 
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}


        


